"""sync_models_with_db

Revision ID: 692c114a7773
Revises: add_template_reviews
Create Date: 2026-06-02 17:17:17.588947
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '692c114a7773'
down_revision: Union[str, None] = 'add_template_reviews'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.alter_column('analytic_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('bot_users', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='to_json(tags)')
    op.alter_column('bot_users', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index('ix_bot_users_bot_id', 'bot_users', ['bot_id'], unique=False)
    op.create_index('ix_bot_users_last_seen_at', 'bot_users', ['last_seen_at'], unique=False)
    op.alter_column('broadcasts', 'target_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='to_json(target_tags)')
    op.alter_column('business_connections', 'can_reply',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('business_connections', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('business_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conv_bot_telegram'), table_name='conversation_messages')
    op.create_index('ix_flow_edges_flow_id', 'flow_edges', ['flow_id'], unique=False)
    op.alter_column('flow_nodes', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index('ix_flow_nodes_flow_id', 'flow_nodes', ['flow_id'], unique=False)
    op.create_index('ix_flow_nodes_flow_id_type', 'flow_nodes', ['flow_id', 'type'], unique=False)
    op.drop_index(op.f('ix_flows_bot_chat_type'), table_name='flows')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_template_reviews_template_id'), table_name='template_reviews')
    op.drop_index(op.f('ix_template_reviews_user_id'), table_name='template_reviews')
    op.alter_column('templates', 'flow_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_index(op.f('ix_templates_creator_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_published'), table_name='templates')
    op.alter_column('webapps', 'layout',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapps', 'layout',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_templates_is_published'), 'templates', ['is_published'], unique=False)
    op.create_index(op.f('ix_templates_creator_id'), 'templates', ['creator_id'], unique=False)
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.alter_column('templates', 'flow_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_template_reviews_user_id'), 'template_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_template_reviews_template_id'), 'template_reviews', ['template_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_flows_bot_chat_type'), 'flows', ['bot_id', 'chat_type'], unique=False)
    op.drop_index('ix_flow_nodes_flow_id_type', table_name='flow_nodes')
    op.drop_index('ix_flow_nodes_flow_id', table_name='flow_nodes')
    op.alter_column('flow_nodes', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('ix_flow_edges_flow_id', table_name='flow_edges')
    op.create_index(op.f('ix_conv_bot_telegram'), 'conversation_messages', ['bot_id', 'telegram_id'], unique=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_connections', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('business_connections', 'can_reply',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('broadcasts', 'target_tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.drop_index('ix_bot_users_last_seen_at', table_name='bot_users')
    op.drop_index('ix_bot_users_bot_id', table_name='bot_users')
    op.alter_column('bot_users', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('bot_users', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('analytic_events', 'event_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###
